name: Test, build and coverage
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '**.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '**.yml'
jobs:
  test-matrix:
    strategy:
      matrix:
        go-version: ['1.19', '1.20']
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}      
      - name: Build binary
        run: make build
      - name: Run tests
        run: make test
      - name: Send code coverage
        uses: codecov/codecov-action@v3
